version: "3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8085
    ports:
      - 8085:8085
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgresdb:5432/library
    depends_on:
      - db
  db:
    container_name: postgresdb
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    ports:
      - '5432:5432'

