DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS(BOOKID BIGINT, AUTHORID BIGINT,
foreign key (BOOKID) references BOOKS(ID) on delete cascade,
foreign key (AUTHORID) references AUTHORS(ID) on delete cascade);
DROP TABLE IF EXISTS BOOKS_GENRES;
CREATE TABLE BOOKS_GENRES(BOOKID BIGINT, GENREID BIGINT,
foreign key (BOOKID) references BOOKS(ID) on delete cascade,
foreign key (GENREID) references GENRES(ID) on delete cascade);