spring:
  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5430/onlineTutoring
    username: usr
    password: pwd
  sql:
    init:
      mode: never
    show-sql: true

  jpa:
    defer-datasource-initialization: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
  port: 8085